name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Permissions for the GitHub Actions
    permissions:
        id-token: write
        contents: read
    env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
    
      # Setup node environment
      - name: Checkout code
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Setup AWS CLI
      - name: Assume AWS role using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ secrets.AWS_REGION }}

      # Install dependencies
      - name: Install client dependencies
        run: cd client && npm install

      # Install infra dependencies
      - name: Install infra dependencies
        run: cd infra && npm install

      # Build client
      - name: Build client
        run: cd client && npm run build
      
      # Deploy
      - name: Deploy
        run: cd infra && npx cdk deploy --require-approval never
